implemented flipping card
king-11/Web_Design pull request #10
Opened 2020-06-09 11:35 UTC by MadhavaDasari

implemented the idea of flipping card

2020-06-12 19:51 UTC, king-11 requested changes
Great Job on transform just a heads up using absolute although gives to total control but also makes the content rigid.

2020-06-12 19:51 UTC, king-11 commented on Flipping Cards/style.css
> +}
instead of this, we can use :after with p and h1 tag because fixing everything will make it rigid.

2020-06-12 19:51 UTC, king-11 commented on Flipping Cards/style.css
> +}
text won't wrap on long lines

2020-06-12 19:51 UTC, king-11 commented on Flipping Cards/style.css
> +    background-image: linear-gradient(white,purple);
Nice :+1:

2020-06-12 19:51 UTC, king-11 commented on Flipping Cards/style.css
> +    position: relative;
great work :100:

2020-06-12 19:51 UTC, king-11 commented on Flipping Cards/style.css
> +}
```suggestion
#f1{
    top:200px;
   width: inherit;
   text-align:center
}

#f2{
    color:purple;
    top:250px;
    width: inherit;
   text-align:center
}

#b1{
    top:10px;
    width: inherit;
   text-align:center
    color: purple;
}
```

2020-06-12 19:51 UTC, king-11 commented on Flipping Cards/style.css
> +}
This will align text more properly

2020-06-13 05:40 UTC, MadhavaDasari commented
@king-11  Thanks for the review .. i  will  definitely consider your suggestions and changes you requested

2020-06-13 09:19 UTC, king-11 approved these changes

2020-06-13 09:19 UTC, merged